version: '3.8'

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: product-trial-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - product-trial-network

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: product-trial-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - product-trial-network

networks:
  product-trial-network:
    driver: bridge
